Feature thebest cab
GomezJuanEfe/go-cab-now pull request #17
Opened 2023-07-24 23:35 UTC by PVARGASM1

Feature the best cab

2023-07-27 21:39 UTC, GomezJuanEfe requested changes
Hacer cambios en los estilos

2023-07-28 01:24 UTC, PVARGASM1 commented
Cambios generados.

2023-07-28 04:09 UTC, GomezJuanEfe approved these changes
Me tomé el atrevimiento de hacer unos cambios en el componente BrandsFleet:
- Se quitaron las flechas y se centraron las imágenes en BrandsFleet
Por último, se resolvieron los conflictos entre las ramas.

2023-07-28 15:45 UTC, danielhincapievargas approved these changes

2023-07-28 15:45 UTC, merged