Feature/payment page
GomezJuanEfe/go-cab-now pull request #26
Opened 2023-08-05 04:55 UTC by PVARGASM1

Hola chicos, 

Me ayudan con revisión y aprobación de las paginas que tenía pendiente.

2023-08-05 18:15 UTC, GomezJuanEfe commented on src/components/NetBanking/NetBanking.scss
> +h6{
Ojo con esto. Al añadir estilos por tag sin tener por lo menos una clase antes, vas a editar los estilos de toda la página. Deberías hacer algo así:
`
.baking-section h6 { 
   ....
}
`

2023-08-05 18:59 UTC, GomezJuanEfe requested changes
Hola, Andre!
Revisa los cambios que te sugiero. Ojo con los estilos y con llamar tags para estilar. En caso de necesitar modificar algo muy general, lo puedes hacer desde un componente padre.

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/MyWallet/MyWallet.scss
> +}
Este h6 está modificando estilos de otras páginas. Debería de estar precedido de una clase.
`.wallet-section h6 { ... }`

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/SuccessBooking/Success.scss
> +}
Este estilo también está modificando otras páginas. Lo mismo, debería estar precedido de una clase.

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/SuccessBooking/Success.scss
> +}
Ojo con la identación

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/Failed/Failed.scss
> +  }
Se está llamando solo el tag. hace falta incluirlo en una clase. Ojo con la identación

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/Failed/Failed.scss
> +  }
Lo mismo, se está llamando solo el tag y está modificando estilos de otras páginas

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/Failed/Failed.scss
> +  }
Igual aquí

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/Payment/Payment.scss
> +    }
Ojo con la identación

2023-08-05 18:59 UTC, GomezJuanEfe commented on src/components/NetBanking/NetBanking.scss
> +}
Lo mismo acá, si necesitar modificar todos los h6 de una página en especial, pueder ir a los estilos de la página o de un componente padre, seleccionar un contenedor que incluya todos componentes e incluir los estilos del h6 ahí

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/NetBanking/NetBanking.scss
> +}
Cambios aplicados según feedback.

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/Payment/Payment.scss
> +    }
Cambios aplicados según feedback.

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/Failed/Failed.scss
> +  }
Cambio aplicado.

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/Failed/Failed.scss
> +  }
Cambio aplicado.

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/Failed/Failed.scss
> +  }
Cambio aplicado.

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/SuccessBooking/Success.scss
> +}
Cambio aplicado

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/SuccessBooking/Success.scss
> +}
Cambio aplicado.

2023-08-06 15:44 UTC, PVARGASM1 commented on src/components/MyWallet/MyWallet.scss
> +}
Cambio aplicado.

2023-08-06 15:47 UTC, PVARGASM1 commented
Hola Juan, 
Todos los cambios fueron aplicados según tu feedback.
Quedo atenta.

2023-08-06 15:51 UTC, danielhincapievargas approved these changes

2023-08-06 17:09 UTC, GomezJuanEfe requested changes
Hola, Andre!

Solo faltó por aplicar unos cambios. Lo dejé ahí en los compentarios. Lo dejas listo y aprovamos los cambios.

Saludos

2023-08-06 17:09 UTC, GomezJuanEfe commented on src/components/NetBanking/NetBanking.scss
> +}
Hola, Andre!
Faltó por aplicar este cambio.

2023-08-07 02:33 UTC, PVARGASM1 commented
Hola Juan, 

Ya arregle los problemas de identación, quedo atenta.

2023-08-08 18:06 UTC, GomezJuanEfe approved these changes
Súper!
Muy buen trabajo!

2023-08-08 18:08 UTC, merged